[project]
name = "CSIRO - Image2Biomass Prediction"
version = "0.1.0"
description = "Predict biomass using the provided pasture images with PyTorch."
readme = "README.md"
requires-python = ">=3.10,<3.13"
dependencies = [
  "ipykernel>=6.30.1",
  "notebook"
]
